### ISSUE TITLE
Question About GPU Dependency for Running Code

### ISSUE THREAD

**Issue by rlawjdgus246** [Bigdasgit/ARIAN#4]
Hello,

I think this research shows great potential, and I am very interested in testing the code.
However, I would like to know if it is possible to run the code in a non-GPU environment, or if GPU is strictly required.

Thank you for your time and clarification!

**Comment by Bigdasgit** [comment]
Here’s a polished and professional response:

Hello,

Thank you for your interest and kind words about our research!

Unfortunately, due to the number of parameters, the code cannot run in a non-GPU environment.
One of our current challenges is to make the model lighter and more efficient.

We appreciate your understanding and support!
