### ISSUE TITLE
Clarification on Config File vs Command Line Arguments

### ISSUE THREAD

**Issue by rlawjdgus246** [Bigdasgit/ARIAN#5]
Hello,

From the code, it appears that both a config file and command line arguments can be used.
Could you clarify the difference between the two and how they interact?

Thank you for your explanation!

**Comment by Bigdasgit** [comment]
Hello,

I apologize for any confusion caused.

There is currently no strict need for the arguments to be separated.
We are working on updating the code so that everything can be controlled with a single config file in the near future.

Thank you for bringing this up, and we appreciate your understanding!
